<?
  // Set page title.
  $this->headTitle($this->translate('Search History'));

  // Set up breadcrumbs:
  $this->layout()->breadcrumbs = '<li><a href="' .  $this->url('myresearch-home') . '">' . $this->transEsc('Your Account') . '</a></li>'
    . '<li class="active">' . $this->transEsc('History') . '</li>';
?>

<div class="row">
  <div class="col-xs-12 col-md-9 line-right">
    <? if (!empty($this->saved)): ?>
      <h2><?=$this->transEsc("history_saved_searches")?></h2>
      <?=$this->context()->renderInContext('search/history-table.phtml', array('showSaved' => true));?>
    <? endif; ?>

    <h2><?=$this->transEsc("history_recent_searches")?></h2>
    <? if (!empty($this->unsaved)): ?>
      <?=$this->context()->renderInContext('search/history-table.phtml', array('showSaved' => false));?>
    <? else: ?>
      <?=$this->transEsc("history_no_searches")?>
    <? endif; ?>
  </div>

  <div class="col-xs-12 col-sm-3 hidden-print">
    <?=$this->context($this)->renderInContext(
        "myresearch/menu.phtml",
        // Only activate search history in account menu if user is logged in.
        $this->auth()->isLoggedIn() ? array('active' => 'history') : array()
      );
    ?>
  </div>
</div>
