<? if (!isset($this->indexStart)) $this->indexStart = 0; ?>
<? $showCheckboxes = (isset($this->showCartControls) && $this->showCartControls) ?>
<? $i = $this->indexStart; foreach ($this->results->getResults() as $current):
  $recordNumber = $this->results->getStartRecord()+$i-$this->indexStart; ?>
  <div id="result<?=$i++ ?>" class="result media">
    <?=$this->record($current)->getSearchResult('list')?>
  </div>
<? endforeach; ?>
