<?
// Set default value if necessary:
if (!isset($this->searchClassId)) {
    $this->searchClassId = 'Solr';
}

// Load search actions and settings (if any):
$options = $this->searchOptions($this->searchClassId);
$handlers = $this->searchbox()->getHandlers(
    $this->searchClassId,
    isset($this->searchIndex) ? $this->searchIndex : null
);
$handlerCount = count($handlers);
$basicSearch = $this->searchbox()->combinedHandlersActive() ? 'combined-searchbox' : $options->getSearchAction();
$searchHome = $options->getSearchHomeAction();
$advSearch = $options->getAdvancedSearchAction();
$lastSort = $this->searchMemory()->getLastSort($this->searchClassId);
$lastLimit = $this->searchMemory()->getLastLimit($this->searchClassId);
?>
<? if ($this->searchType == 'advanced'): ?>
    <div id="searchForm">
        <? $searchTabs = $this->searchtabs($this->searchClassId, $this->lookfor, $this->searchIndex, $this->searchType); ?>


        <div class="tab-content clearfix">
        <br><br>
            <p><?=$this->transEsc("Your search terms")?> : "<strong><?=$this->escapeHtml($this->lookfor)?>"</strong></p>
            <p class="adv_search_links">
                <a href="<?=$this->url($advSearch)?>?edit=<?=$this->escapeHtmlAttr($this->searchId)?>"><?=$this->transEsc("Edit this Advanced Search")?></a>
                <a href="<?=$this->url($advSearch)?>"><?=$this->transEsc("Start a new Advanced Search")?></a>
                <a href="<?=$this->url($searchHome)?>"><?=$this->transEsc("Start a new Basic Search")?></a>
            </p>

        </div>

    </div>
<? else: ?>
    <form role="search" class="search form-table" method="get" action="<?=$this->url($basicSearch)?>" name="searchForm" id="searchForm" autocomplete="off">
        <div class="form-group" id="autoCompleteContainer">
            <label class="sr-only" for="lookfor">Vyhledávat:</label>
	    <input class="form-control search-query<? if($this->searchbox()->autocompleteEnabled($this->searchClassId)):?> autocomplete searcher:<?=$this->escapeHtmlAttr($this->searchClassId) ?><? endif ?>" id="lookfor" type="text" name="lookfor" size="30" placeholder="<?=$this->transEsc('integrated_search')?>" value="<?=$this->escapeHtmlAttr($this->lookfor)?>" x-webkit-speech speech />
        </div>
        <div class="form-group" id="search-select">
            <label class="sr-only" for="lookfor">Typ pole:</label>
            <? if ($handlerCount > 1): ?>
                <select class="form-control" id="searchForm_type" name="type" data-native-menu="false">
                    <? foreach ($handlers as $handler): ?>
                        <option value="<?=$this->escapeHtmlAttr($handler['value'])?>"<?=$handler['selected'] ? ' selected="selected"' : ''?>><?=$handler['indent'] ? '-- ' : ''?><?=$this->transEsc($handler['label'])?></option>
                    <? endforeach; ?>
                </select>
            <? elseif ($handlerCount == 1): ?>
                <input type="hidden" name="type" value="<?=$this->escapeHtmlAttr($handlers[0]['value'])?>" />
            <? endif; ?>
        </div>
        <div class="form-group cell-minimal">
            <button type="submit" class="btn btn-primary"><i class="fa fa-search"></i> <?=$this->transEsc("Find")?></button>
        </div>

        <? if ($advSearch): ?>

<!--            --><?// if (($this->searchType == 'basic') || (strpos($_SERVER["REQUEST_URI"], 'Record') == true) || (strpos($_SERVER["REQUEST_URI"], 'MyResearch') == true) || (!empty($_SERVER["REDIRECT_accountID"]))): ?>
<!--                <div class="search-links">-->
<!--            --><?// endif; ?>

<!--        --><?// if ($this->layout()->searchbox !== false): ?>
<!--            <div class="search-links">-->
<!--        --><?// endif; ?>
            <?
                if (preg_match("/_ga/i", $_SERVER["REQUEST_URI"])) {
                    $request_uri = preg_replace('/\?_ga.*/i', '', $_SERVER["REQUEST_URI"]);
                } else {
                    $request_uri = $_SERVER["REQUEST_URI"];
                }
            ?>
<!--            odkaz na domovske strance   -->
            <?if (($request_uri == $this->url('home')) || ($request_uri == $this->url('home').'Search/Home') || ($request_uri == $this->url('home').'Summon/Home')): ?>
                            <div class="form-group cell-minimal">
                                <a class="btn btn-link" href="<?=$this->url($advSearch)?>"><?=$this->transEsc("Advanced Search")?></a>
                            </div>
            <? else: ?>
<!--            odkaz vsude jinde   -->
                            <div class="search-links">
                                <a href="<?=$this->url($advSearch)?>"><?=$this->transEsc("Advanced Search")?></a>
            <? endif; ?>



            <? if ($this->searchType == 'basic'): ?>
                <? $shards = $options->getShards(); if ($options->showShardCheckboxes() && !empty($shards)): ?>
                    <?
                    $selectedShards = isset($this->selectedShards)
                        ? $this->selectedShards : $options->getDefaultSelectedShards();
                    ?>
                    <br />
                    <? foreach ($shards as $shard => $val): ?>
                        <? $isSelected = empty($selectedShards) || in_array($shard, $selectedShards); ?>
                        <input type="checkbox" <?=$isSelected ? 'checked="checked" ' : ''?>name="shard[]" value='<?=$this->escapeHtmlAttr($shard)?>' /> <?=$this->transEsc($shard)?>
                    <? endforeach; ?>
                <? endif; ?>
                <?
                $filterDetails = $this->searchbox()->getFilterDetails(
                    isset($this->filterList) && is_array($this->filterList) ? $this->filterList : array(),
                    isset($this->checkboxFilters) && is_array($this->checkboxFilters) ? $this->checkboxFilters : array()
                );
                ?>
                <? if ((isset($hasDefaultsApplied) && $hasDefaultsApplied) || !empty($filterDetails)): ?>
                    <? $defaultFilterState = $options->getRetainFilterSetting() ? ' checked="checked"' : ''; ?>
                    <div class="checkbox">
                        <label>
                            <input type="checkbox"<?=$defaultFilterState?> id="searchFormKeepFilters"/>
                            <input onChange="$('.applied-filter').click()" type="checkbox"<?=$defaultFilterState?> id="searchFormKeepFilters"/>
                            <?=$this->transEsc("basic_search_keep_filters")?>
                        </label>
                    </div>
                    <div class="hidden">
                        <? foreach ($filterDetails as $current): ?>
                            <input class="applied-filter" id="<?=$this->escapeHtmlAttr($current['id'])?>" type="checkbox"<?=$defaultFilterState?> name="filter[]" value="<?=$this->escapeHtmlAttr($current['value'])?>" />
                            <label for="<?=$this->escapeHtmlAttr($current['id'])?>"><?=$this->escapeHtml($current['value'])?></label>
                        <? endforeach; ?>
                        <? if (isset($hasDefaultsApplied) && $hasDefaultsApplied): ?>
                            <!-- this is a hidden element that flags whether or not default filters have been applied;
                                 it is intentionally unlabeled, as users are not meant to manipulate it directly. -->
                            <input class="applied-filter" id="dfApplied" type="checkbox" name="dfApplied" value="1"<?=$defaultFilterState?> />
                        <? endif; ?>
                    </div>
                <? endif; ?>


<!--                --><?// if (($this->searchType == 'basic') || (strpos($_SERVER["REQUEST_URI"], 'Record') == true) || (strpos($_SERVER["REQUEST_URI"], 'MyResearch') == true) || (!empty($_SERVER["REDIRECT_accountID"]))): ?>
<!--                    </div>-->
<!--                --><?// endif; ?>

<!--                --><?// if ($this->layout()->searchbox !== false): ?>
<!--                    </div>-->
<!--                --><?// endif; ?>


            <? endif; ?>

            <?if (($request_uri == $this->url('home')) || ($request_uri == $this->url('home').'Search/Home') || ($request_uri == $this->url('home').'Summon/Home')): ?>

            <? else: ?>
                </div>
            <? endif; ?>



        <? endif; ?>

        <?
        /* Show hidden field for active search class when in combined handler mode. */
        if ($this->searchbox()->combinedHandlersActive()) {
            echo '<input type="hidden" name="activeSearchClassId" value="' . $this->escapeHtmlAttr($this->searchClassId) . '" />';
        }
        /* Load hidden limit preference from Session */
        if (!empty($lastLimit)) {
            echo '<input type="hidden" name="limit" value="' . $this->escapeHtmlAttr($lastLimit) . '" />';
        }
        if (!empty($lastSort)) {
            echo '<input type="hidden" name="sort" value="' . $this->escapeHtmlAttr($lastSort) . '" />';
        }
        ?>
    </form>
    <script type="text/javascript">$("#searchForm_lookfor").focus()</script>
<? endif; ?>
