<? /* Display thumbnail if appropriate: */ ?>
<? if ($cover): ?>
  <? $id = $this->driver->getUniqueId(); ?>
  <? if ($this->link): ?><a href="../img-box.php?uid=<?=$id?>" data-lightbox data-lightbox-title="<?=$this->escapeHtmlAttr(' ')?>"><? endif; ?>
  <img alt="<?=$this->transEsc('Cover Image')?>" class="recordcover" src="<?=$this->escapeHtmlAttr($cover); ?>"/>
  <? if ($this->link): ?></a><? endif; ?>
<? else: ?>
  <img src="<?=$this->url('cover-unavailable')?>" class="recordcover" alt="<?=$this->transEsc('No Cover Image')?>"/>
<? endif; ?>
