<?
    // Set up page title:
    $this->headTitle($this->translate('Checked Out History'));

    // Set up breadcrumbs:
    $this->layout()->breadcrumbs = '<li><a href="' . $this->url('myresearch-home') . '">' . $this->transEsc('Your Account') . '</a></li> <li class="active">' . $this->transEsc('Checked Out History') . '</li>';
?>
<div class="row">
<div class="col-xs-12 col-md-9 line-right">
  <h2><?=$this->transEsc('Your Checked Out History')?></h2>
  <?=$this->flashmessages()?>

	<? if ((isset($_GET["limit"])) || (sizeof($this->transactions) < 20)):?>
		<?=$this->transEsc('list of all items')?>
	<? else: ?>
		<?=$this->transEsc('list of 20 items')?>
	<? endif; ?>

    <? if (!empty($this->transactions)): ?>
	 <? $i = 0; foreach ($this->transactions as $resource): ?>
	 	<hr/>
		<? $ilsDetails = $resource->getExtraDetail('ils_details'); ?>
		<div id="record<?=$this->escapeHtmlAttr($resource->getUniqueId())?>" class="result media">
		<div class="media-left">
			<? if ($summThumb = $this->record($resource)->getThumbnail()): ?>
                            <img src="<?=$this->escapeHtmlAttr($summThumb)?>" class="media-object recordcover" alt="<?=$this->transEsc('Cover Image')?>"/>
                        <? else: ?>
                            <img src="<?=$this->url('cover-unavailable')?>" class="media-object recordcover" alt="<?=$this->transEsc('No Cover Image')?>"/>
                        <? endif; ?>
		</div>
		<div class="media-body">
                	<h3 class="media-heading">
			<?
                       	// If this is a non-missing Solr record, we should display a link:
    			if (is_a($resource, 'VuFind\\RecordDriver\\SolrDefault') && !is_a($resource, 'VuFind\\RecordDriver\\Missing'))
			{			
				$title = $resource->getTitle();
				$title = empty($title) ? $this->transEsc('Title not available') : $this->escapeHtml($title);
			        echo '<a href="' . $this->recordLink()->getUrl($resource) . '" class="title">' . $title . '</a>';
			} else if (isset($ilsDetails['title']) && !empty($ilsDetails['title'])){
			// If the record is not available in Solr, perhaps the ILS driver sent us a title we can show...
				echo $this->escapeHtml($ilsDetails['title']);
			} else {
			// Last resort -- indicate that no title could be found.
                        echo $this->transEsc('Title not available');
                        }
                        ?>
			</h3>
			<small>
			<? $listAuthor = $resource->getPrimaryAuthor(); if (!empty($listAuthor)): ?>
              			<span class="text-muted"><?=$this->transEsc('by')?>:</span>
				<a href="<?=$this->record($resource)->getLink('author', $listAuthor)?>"><?=$this->escapeHtml($listAuthor)?></a><br/>
			<? endif; ?>
			</small>
			<div class="result-meta">
			<? $formats = $resource->getFormats(); if (count($formats) > 0): ?>
                            <?=str_replace('class="', 'class="', $this->record($resource)->getFormatList())?>
                            <br/>
                        <? endif; ?>
			<? if (isset($ilsDetails['volume']) && !empty($ilsDetails['volume'])): ?>
				<strong><?=$this->transEsc('Volume')?>:</strong> <?=$this->escapeHtml($ilsDetails['volume'])?>
				<br />
			<? endif; ?>
	                <? if (isset($ilsDetails['publication_year']) && !empty($ilsDetails['publication_year'])): ?>
			<strong><?=$this->transEsc('Year of Publication')?>:</strong> <?=$this->escapeHtml($ilsDetails['publication_year'])?>
			<br />
	                <? endif; ?>
                	<? if (isset($ilsDetails['duedate'])): ?>
				<strong><?=$this->transEsc('Due Date')?>: <?=$this->escapeHtml($ilsDetails['duedate'])?><? if (isset($ilsDetails['dueTime'])): ?> <?=$this->escapeHtml($ilsDetails['dueTime'])?><? endif; ?></strong>
			        <br />
		        <? endif; ?>
    			<? if (isset($ilsDetails['returned'])): ?>
		              <strong><?=$this->transEsc('Returned')?>: <?=$this->escapeHtml($ilsDetails['returned'])?></strong>
			<? endif; ?>
			</div>
		</div>
		</div><!-- record -->
		<? endforeach; ?>

		<? if (!isset($_GET["limit"])):?>
			<?=$this->transEsc('display_all_checkout_history')?>
			<a onclick="myFunction()" href="<?=$this->url('myresearch-checkedouthistory', array('limit' => '0'), array('query' => array('limit' => 0,)))?>"><?=$this->transEsc('here')?></a>.
			<?=$this->transEsc('checkout_history_wait')?>
		<? endif; ?>

		<script>
			function myFunction() {
				$('#modal').modal('show');
			}
		</script>

	    <? else: ?>
		<?=$this->transEsc('You do not have any items checked out')?>.
	    <? endif; ?>

    </div>

    <div class="col-xs-12 col-sm-3 hidden-print">
        <?=$this->context($this)->renderInContext("myresearch/menu.phtml", array('active' => 'checkedouthistory'))?>
    </div>
</div>
