<?
    // Set up page title:
    $this->headTitle($this->translate('My Fines'));

    // Set up breadcrumbs:
    $this->layout()->breadcrumbs = '<li><a href="' . $this->url('myresearch-home') . '">' . $this->transEsc('Your Account') . '</a></li> <li class="active">' . $this->transEsc('Fines') . '</li>';
?>
<div class="row">
<div class="col-xs-12 col-md-9 line-right">
  <h2><?=$this->transEsc('Your Fines')?></h2>
  <? if (empty($this->fines)): ?>
    <?=$this->transEsc('You do not have any fines')?>
  <? else: ?>
    <table class="table table-striped" summary="<?=$this->transEsc('Your Fines')?>">
    <tr>
      <th><?=$this->transEsc('Title')?></th>
      <th><?=$this->transEsc('Returned')?></th>
      <th><?=$this->transEsc('Due Date')?></th>
      <th></th>
      <th></th>
      <th><?=$this->transEsc('Balance')?></th>
    </tr>
    <? $totalDue = 0; ?>
    <? foreach ($this->fines as $record): ?>
      <tr>
        <td>
          <? if (empty($record['title'])): ?>
            <?=$this->transEsc('not_applicable')?>
          <? elseif (!isset($record['id'])): ?>
            <?=$this->escapeHtml(trim($record['title'], '/:'))?>
          <? else: ?>
            <a href="<?=$this->url('record', array('id' => $record['id']))?>"><?=$this->escapeHtml(trim($record['title'], '/:'))?></a>
          <? endif; ?>
        </td>
        <td><?=isset($record['checkout']) ? $this->escapeHtml($record['checkout']) : ''?></td>
        <td><?=isset($record['duedate']) ? $this->escapeHtml($record['duedate']) : ''?></td>
        <td></td>
        <td></td>
        <td><?=isset($record['amount']) ? $this->safeMoneyFormat($record['amount']/100.00) : ''?></td>
      </tr>
      <? $totalDue += $record['amount']; ?>
    <? endforeach; ?>
      <tr style="font-weight:bold"><td colspan="5"><?=$this->transEsc('Total Balance Due')?></td><td><?=$this->safeMoneyFormat($totalDue/100.00) ?></td></tr>
    </table>
  <? endif; ?>
</div>

<div class="col-xs-12 col-sm-3 hidden-print">
  <?=$this->context($this)->renderInContext("myresearch/menu.phtml", array('active' => 'fines'))?>
</div>
</div>
