<?
  // Set page title.
  $this->headTitle($this->translate('Advanced Search'));

  // Disable top search box -- this page has a special layout.
  $this->layout()->searchbox = false;

  // Set up breadcrumbs:
  $this->layout()->breadcrumbs = '<li>';
  $lastSearchLink = $this->searchMemory()->getLastSearchLink($this->transEsc('Search'));
  $this->layout()->breadcrumbs .= !empty($lastSearchLink)
    ? $lastSearchLink : $this->transEsc('Search');
  $this->layout()->breadcrumbs .= '</li> <li class="active">' . $this->transEsc('Advanced') . '</li>';

  // Set up saved search details:
  if (isset($this->saved) && is_object($this->saved)) {
    $searchDetails = $this->saved->getParams()->getQuery();
    if ($searchDetails instanceof \VuFindSearch\Query\Query) {
        // Not an advanced query -- ignore it.
        $searchDetails = $groups = false;
    } else {
        $groups = $searchDetails->getQueries();
    }
    $hasDefaultsApplied = $this->saved->getParams()->hasDefaultsApplied();
    $searchFilters = $this->saved->getParams()->getFilterList();
    $hiddenFilters = $this->saved->getParams()->getHiddenFilters();
  } else {
    $hasDefaultsApplied = $searchDetails = $searchFilters = $groups = false;
    $hiddenFilters = $this->searchtabs()->getHiddenFilters($this->searchClassId, true);
  }

  // Step 1: Load the javascript
  $this->headScript()->appendFile(
    isset($this->advancedSearchJsOverride) ? $this->advancedSearchJsOverride : 'advanced_search.js'
  );
  // Step 2: Build the page
  $this->headScript()->appendScript(
    $this->partial(
      isset($this->buildPageOverride) ? $this->buildPageOverride : 'search/advanced/build_page.phtml',
      ['options' => $this->options, 'searchDetails' => $searchDetails]
    )
  );
  // Step 3: Define our search arrays so they are usuable in the javascript
  $this->headScript()->appendScript($this->render('search/advanced/globals.phtml'));
  
  // Collect previous search queries
  $setSearchGroups = [];
  $setGroupCount = 0;
  $setQueries = [];
  if (isset($searchDetails) && is_object($searchDetails)) {
    foreach ($searchDetails->getQueries() as $group=>$searchGroup) {
      $setSearchGroups[$group] = $searchGroup->isNegated() ? 'NOT' : $searchGroup->getOperator();
      if ($setGroupCount < $group) {
        $setGroupCount = $group;
      }
      if (!isset($setQueries[$group])) {
        $setQueries[$group] = [];
      }
      foreach ($searchGroup->getQueries() as $search) {
        $setQueries[$group][] = $search;
      }
    }
  }
?>

<?=$this->flashmessages()?>
<h2><?=$this->transEsc('Advanced Search')?></h2>
<form role="search" name="searchForm" id="advSearchForm" method="get" action="<?=$this->url($this->options->getSearchAction())?>">
  <div class="row">
    <div class="col-xs-12 col-md-9">
<!--      <div class="--><?//=$this->layoutClass('mainbody')?><!--">-->
      <div class="form-horizontal">
        <input type="hidden" name="sort" value="relevance">
        <fieldset>
<!-- Přepínač: Shoda -->
            <div id="groupJoin" class="fieldset-options form-inline">
              <div class="form-group">
                <label for="join"><?=$this->transEsc("search_match")?>:</label>
                <select id="search_bool0" name="join" class="form-control input-sm">
                  <option value="AND"<? if($searchDetails && $searchDetails->getOperator()=='ALL'):?> selected<?endif?>><?= $this->transEsc('group_AND') ?></option>
                  <option value="OR"<? if($searchDetails && $searchDetails->getOperator()=='OR'):?> selected<?endif?>><?= $this->transEsc('group_OR') ?></option>
                </select>
              </div>
            </div>

            <legend><?=$this->transEsc("search_groups")?></legend>

<!-- Přidat vyhledávací skupinu -->
            <div class="group" id="groupPlaceHolder">
              <a class="btn btn-sm btn-link" href="#" onClick="addGroup()"><i class="glyphicon glyphicon-plus-sign"></i> <?= $this->transEsc('add_search_group') ?></a>
            </div>
        </fieldset>

<!--        <input class="btn btn-primary" type="submit" value="--><?//= $this->transEsc('Find')?><!--">-->
        <? if (isset($this->extraAdvancedControls)): ?>
          <?=$this->extraAdvancedControls ?>
          <input class="btn btn-primary" type="submit" value="<?= $this->transEsc('Find')?>"/>
        <? endif; ?>
      </div>
<!--      </div>-->
    </div>
    <div class="sidebar col-xs-12 col-md-3 hidden-print">
<!--      <div class="--><?//=$this->layoutClass('sidebar')?><!--">-->
        <? if ($hasDefaultsApplied): ?>
          <input type="hidden" name="dfApplied" value="1" />
        <? endif ?>
        <? if (!empty($searchFilters)): ?>
          <h4><?=$this->transEsc("adv_search_filters")?></h4>
          <ul class="list-group">
            <li class="list-group-item">
                <label class="checkbox"><?=$this->transEsc("adv_search_select_all")?> <input type="checkbox" checked="checked" class="checkbox-select-all"/></label>
            </li>
          </ul>
          <? foreach ($searchFilters as $field => $data): ?>
            <ul class="list-group">
              <li class="list-group-item title"><?=$this->transEsc($field)?></li>
              <? foreach ($data as $value): ?>
                <li class="list-group-item">
                    <label class="checkbox"><input class="checkbox-select-item" type="checkbox" checked="checked" name="filter[]" value='<?=$this->escapeHtmlAttr($value['field'])?>:"<?=$this->escapeHtmlAttr($value['value'])?>"' /> <?=$this->escapeHtml($value['displayText'])?></label>
                </li>
              <? endforeach; ?>
            </ul>
          <? endforeach; ?>
        <? endif; ?>
<!--        <div class="sidegroup">-->
          <h3 class="secondary"><?=$this->transEsc("Search Tips")?></h4>
          <ul>
            <li><a class="help-link" data-lightbox href="<?=$this->url('help-home')?>?topic=advsearch"><?=$this->transEsc("Help with Advanced Search")?></a></li>
            <li><a class="help-link" data-lightbox href="<?=$this->url('help-home')?>?topic=search"><?=$this->transEsc("Help with Search Operators")?></a></li>
          </ul>
<!--        </div>-->
<!--      </div>-->
    </div>
  </div>
</form>
