<?
  $addThis = $this->addThis();
  if (!empty($addThis)) {
    $this->headScript()->appendFile('https://s7.addthis.com/js/250/addthis_widget.js?pub=' . urlencode($addThis));
  }

  // Set up some variables for convenience:
  $id = $this->driver->getUniqueId();
  $controllerClass = 'controller:' . $this->record($this->driver)->getController();
  $cart = $this->cart();
  $cartId = $this->driver->getSourceIdentifier() . '|' . $id;
?>
<div class="btn-toolbar hidden-print" role="toolbar" aria-label="...">
  <? if (count($this->driver->getCitationFormats()) > 0): ?>
  <div class="btn-group" role="group" aria-label="...">
    <a id="cite-record" class="btn btn-sm btn-default <?=$controllerClass?>" data-lightbox data-lightbox-title="<?=$this->transEsc('Cite this')?>" href="<?=$this->recordLink()->getActionUrl($this->driver, 'Cite')?>" title="<?=$this->transEsc('Cite this')?>" rel="nofollow"><i class="fa fa-asterisk"></i> <?=$this->transEsc('Cite this')?></a></li>
  </div>
  <? endif; ?>
<!-- NTK doesn't support SMS sending yet
  <div class="btn-group" role="group" aria-label="...">
    <a id="sms-record" class="btn btn-sm btn-default <?=$controllerClass?>" data-lightbox href="<?=$this->recordLink()->getActionUrl($this->driver, 'SMS')?>" rel="nofollow"><i class="fa fa-mobile"></i> <?=$this->transEsc('Text this')?></a>
  </div>
-->
  <div class="btn-group" role="group" aria-label="...">
    <a id="mail-record" class="btn btn-sm btn-default <?=$controllerClass?>" data-lightbox data-lightbox-title="<?=$this->transEsc('Email this')?>: <?=$this->escapeHtml($this->driver->getShortTitle() . ' ' . $this->driver->getSubtitle() . ' ' . $this->driver->getTitleSection())?>" href="<?=$this->recordLink()->getActionUrl($this->driver, 'Email')?>" title="<?=$this->transEsc('Email this')?>" rel="nofollow"><i class="fa fa-envelope"></i> <?=$this->transEsc('Email this')?></a></li>
  </div>

  <? $exportFormats = $this->export()->getFormatsForRecord($this->driver); ?>
  <? if(count($exportFormats) > 0): ?>
    <div class="btn-group dropdown" role="group" aria-label="...">
      <a class="btn btn-sm btn-default export-toggle dropdown-toggle" data-toggle="dropdown" href="<?=$this->recordLink()->getActionUrl($this->driver, 'Export')?>" title="<?=$this->transEsc('Export to')?>" rel="nofollow"><i class="glyphicon glyphicon-list-alt"></i> <?=$this->transEsc('Export Record') ?></a>
      <ul class="dropdown-menu" role="menu">
        <? foreach ($exportFormats as $exportFormat): ?>
          <li><a <? if ($this->export()->needsRedirect($exportFormat)): ?>target="<?=$this->escapeHtmlAttr($exportFormat)?>Main" <? endif; ?>href="<?=$this->recordLink()->getActionUrl($this->driver, 'Export')?>?style=<?=$this->escapeHtmlAttr($exportFormat)?>" rel="nofollow"><?=$this->transEsc('Export to')?> <?=$this->transEsc($this->export()->getLabelForFormat($exportFormat))?></a></li>
        <? endforeach; ?>
      </ul>
    </div>
  <? endif; ?>

  <? if ($this->userlist()->getMode() !== 'disabled'): ?>
  <div class="btn-group" role="group" aria-label="...">
    <a id="save-record" class="btn btn-sm btn-default <?=$controllerClass?>" data-lightbox href="<?=$this->recordLink()->getActionUrl($this->driver, 'Save')?>" rel="nofollow" title="<?=$this->transEsc('Add to favorites')?>"><i class="fa fa-plus"></i> <?=$this->transEsc('Add to favorites')?></a></li>
  </div>
  <? endif; ?>
  <? if (!empty($addThis)): ?>
    <li><a class="addThis addthis_button" href="https://www.addthis.com/bookmark.php?v=250&amp;pub=<?=urlencode($addThis)?>"><i class="fa fa-bookmark"></i> <?=$this->transEsc('Bookmark')?></a></li>
  <? endif; ?>
  <? if ($cart->isActive()): ?>
    <li class="bookbag-menu">
      <input class="cartId" type="hidden" name="ids[]" value="<?=$this->escapeHtmlAttr($cartId)?>" />
      <a class="cart-addi hidden<? if(!$cart->contains($cartId)): ?>correct <? endif ?>" href="#"><i class="fa fa-plus"></i> <?=$this->transEsc('Add to Book Bag') ?></a>
      <a class="cart-remove hidden<? if($cart->contains($cartId)): ?>correct <? endif ?>" href="#"><i class="fa fa-minus-circle"></i> <?=$this->transEsc('Remove from Book Bag') ?></a>
      <noscript>
        <form method="post" name="addForm" action="<?=$this->url('cart-processor')?>">
          <input type="hidden" name="ids[]" value="<?=$this->escapeHtmlAttr($cartId)?>" />
          <? if ($cart->contains($cartId)): ?>
            <input class="btn btn-default" type="submit" name="delete" value="<?=$this->transEsc('Remove from Book Bag')?>"/>
          <? else: ?>
            <input class="btn btn-default" type="submit" name="add" value="<?=$this->transEsc('Add to Book Bag')?>"/>
          <? endif; ?>
        </form>
      </noscript>
    </li>
  <? endif; ?>
</div>
